[package]
name = "day_11_puzzle_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_utils = { path= "../../../aoc_utils" }
regex = "1"
num-bigint = "0.4"